### ISSUE TITLE
FetchError: invalid json response body

### ISSUE THREAD

**Issue by wilkam-C** [DanielZambelli/cvr-explorer#1]
Hey man, awesome work on this project.

I've gotten access to CVR through my friend who has a company in Denmark. I am playing around with it, but I just cant seem to get it to work. I am trying to lookup a CVR and I get this error: Unexpected token < in JSON at position 0. It seems like fetching annual reports work, and I get a pdfUrl aswell as a xmlUrl (although opening them in the browser doesn't load anything). I enclosed some screenshots.

I am very new to Node and JS, and I might be in way over my head - I really just want to see it work!

![webstorm64_BCSjWU77gs](https://user-images.githubusercontent.com/75221733/100564240-c418c780-32c0-11eb-9ce8-d36f23772f7f.png)

**Comment by wilkam-C** [comment]
Didn't actually have access...

**Comment by DanielZambelli** [comment]
Hi @wilkam-C Appreciate your interest! Did it work out? Otherwise I am glad to debug it with you.
